from __future__ import annotations

from core.agent_runtime import hive_topic_draft_parsing as agent_hive_topic_draft_parsing
from core.agent_runtime import hive_topic_draft_variants as agent_hive_topic_draft_variants

clean_hive_title = agent_hive_topic_draft_parsing.clean_hive_title
extract_hive_topic_create_draft = agent_hive_topic_draft_parsing.extract_hive_topic_create_draft
extract_original_hive_topic_create_draft = agent_hive_topic_draft_parsing.extract_original_hive_topic_create_draft

check_hive_duplicate = agent_hive_topic_draft_variants.check_hive_duplicate
build_hive_create_pending_variants = agent_hive_topic_draft_variants.build_hive_create_pending_variants
normalize_hive_create_variant = agent_hive_topic_draft_variants.normalize_hive_create_variant
wants_hive_create_auto_start = agent_hive_topic_draft_variants.wants_hive_create_auto_start
looks_like_hive_topic_create_request = agent_hive_topic_draft_variants.looks_like_hive_topic_create_request
looks_like_hive_topic_drafting_request = agent_hive_topic_draft_variants.looks_like_hive_topic_drafting_request
