from __future__ import annotations

from core.agent_runtime import hive_topic_pending_confirmation as agent_hive_topic_pending_confirmation
from core.agent_runtime import hive_topic_pending_store as agent_hive_topic_pending_store
from core.agent_runtime import hive_topic_preview_render as agent_hive_topic_preview_render

HIVE_CONFIRM_POSITIVE_STRICT = agent_hive_topic_pending_confirmation.HIVE_CONFIRM_POSITIVE_STRICT
HIVE_CONFIRM_POSITIVE_LOOSE = agent_hive_topic_pending_confirmation.HIVE_CONFIRM_POSITIVE_LOOSE
HIVE_CONFIRM_NEGATIVE = agent_hive_topic_pending_confirmation.HIVE_CONFIRM_NEGATIVE

maybe_handle_hive_create_confirmation = agent_hive_topic_pending_confirmation.maybe_handle_hive_create_confirmation
is_pending_hive_create_confirmation_input = agent_hive_topic_pending_confirmation.is_pending_hive_create_confirmation_input
parse_hive_create_variant_choice = agent_hive_topic_pending_confirmation.parse_hive_create_variant_choice

has_pending_hive_create_confirmation = agent_hive_topic_pending_store.has_pending_hive_create_confirmation
remember_hive_create_pending = agent_hive_topic_pending_store.remember_hive_create_pending
clear_hive_create_pending = agent_hive_topic_pending_store.clear_hive_create_pending
load_pending_hive_create = agent_hive_topic_pending_store.load_pending_hive_create
recover_hive_create_pending_from_history = agent_hive_topic_pending_store.recover_hive_create_pending_from_history

format_hive_create_preview = agent_hive_topic_preview_render.format_hive_create_preview
preview_text_snippet = agent_hive_topic_preview_render.preview_text_snippet
