from __future__ import annotations

from core.agent_runtime import hive_topic_create_preflight as agent_hive_topic_create_preflight
from core.agent_runtime import hive_topic_drafting as agent_hive_topic_drafting
from core.agent_runtime import hive_topic_pending as agent_hive_topic_pending
from core.agent_runtime import hive_topic_public_copy as agent_hive_topic_public_copy
from core.agent_runtime import hive_topic_publish_flow as agent_hive_topic_publish_flow

maybe_handle_hive_topic_create_request = agent_hive_topic_create_preflight.maybe_handle_hive_topic_create_request
execute_confirmed_hive_create = agent_hive_topic_publish_flow.execute_confirmed_hive_create
hive_topic_create_failure_text = agent_hive_topic_publish_flow.hive_topic_create_failure_text

prepare_public_hive_topic_copy = agent_hive_topic_public_copy.prepare_public_hive_topic_copy
sanitize_public_hive_text = agent_hive_topic_public_copy.sanitize_public_hive_text
shape_public_hive_admission_safe_copy = agent_hive_topic_public_copy.shape_public_hive_admission_safe_copy
has_structured_hive_public_brief = agent_hive_topic_public_copy.has_structured_hive_public_brief
looks_like_raw_chat_transcript = agent_hive_topic_public_copy.looks_like_raw_chat_transcript
infer_hive_topic_tags = agent_hive_topic_public_copy.infer_hive_topic_tags
normalize_hive_topic_tag = agent_hive_topic_public_copy.normalize_hive_topic_tag
strip_wrapping_quotes = agent_hive_topic_public_copy.strip_wrapping_quotes

maybe_handle_hive_create_confirmation = agent_hive_topic_pending.maybe_handle_hive_create_confirmation
has_pending_hive_create_confirmation = agent_hive_topic_pending.has_pending_hive_create_confirmation
is_pending_hive_create_confirmation_input = agent_hive_topic_pending.is_pending_hive_create_confirmation_input
format_hive_create_preview = agent_hive_topic_pending.format_hive_create_preview
preview_text_snippet = agent_hive_topic_pending.preview_text_snippet
parse_hive_create_variant_choice = agent_hive_topic_pending.parse_hive_create_variant_choice
remember_hive_create_pending = agent_hive_topic_pending.remember_hive_create_pending
clear_hive_create_pending = agent_hive_topic_pending.clear_hive_create_pending
load_pending_hive_create = agent_hive_topic_pending.load_pending_hive_create
recover_hive_create_pending_from_history = agent_hive_topic_pending.recover_hive_create_pending_from_history

check_hive_duplicate = agent_hive_topic_drafting.check_hive_duplicate
clean_hive_title = agent_hive_topic_drafting.clean_hive_title
extract_hive_topic_create_draft = agent_hive_topic_drafting.extract_hive_topic_create_draft
extract_original_hive_topic_create_draft = agent_hive_topic_drafting.extract_original_hive_topic_create_draft
build_hive_create_pending_variants = agent_hive_topic_drafting.build_hive_create_pending_variants
normalize_hive_create_variant = agent_hive_topic_drafting.normalize_hive_create_variant
wants_hive_create_auto_start = agent_hive_topic_drafting.wants_hive_create_auto_start
looks_like_hive_topic_create_request = agent_hive_topic_drafting.looks_like_hive_topic_create_request
looks_like_hive_topic_drafting_request = agent_hive_topic_drafting.looks_like_hive_topic_drafting_request
