from __future__ import annotations

from core.public_hive import bridge_topics
from core.public_hive.bridge_topic_claim_writes import PublicHiveBridgeTopicClaimWritesMixin
from core.public_hive.bridge_topic_lifecycle_writes import PublicHiveBridgeTopicLifecycleWritesMixin
from core.public_hive.bridge_topic_post_progress_writes import PublicHiveBridgeTopicPostProgressWritesMixin
from core.public_hive.bridge_topic_post_result_writes import PublicHiveBridgeTopicPostResultWritesMixin
from core.public_hive.bridge_topic_post_status_writes import PublicHiveBridgeTopicPostStatusWritesMixin
from core.public_hive.bridge_topic_post_writes import PublicHiveBridgeTopicPostWritesMixin
from core.public_hive.bridge_topic_publication import PublicHiveBridgeTopicPublicationMixin
from core.public_hive.bridge_topic_reads import PublicHiveBridgeTopicReadsMixin
from core.public_hive.bridge_topic_reviews import PublicHiveBridgeTopicReviewsMixin
from core.public_hive.bridge_topic_writes import PublicHiveBridgeTopicWritesMixin


def test_public_hive_bridge_topics_split_keeps_read_methods_on_facade() -> None:
    assert issubclass(bridge_topics.PublicHiveBridgeTopicsMixin, PublicHiveBridgeTopicReadsMixin)
    assert bridge_topics.PublicHiveBridgeTopicsMixin.list_public_topics is PublicHiveBridgeTopicReadsMixin.list_public_topics


def test_public_hive_bridge_topics_split_keeps_review_and_write_methods_on_facade() -> None:
    assert issubclass(bridge_topics.PublicHiveBridgeTopicsMixin, PublicHiveBridgeTopicReviewsMixin)
    assert issubclass(bridge_topics.PublicHiveBridgeTopicsMixin, PublicHiveBridgeTopicWritesMixin)
    assert issubclass(PublicHiveBridgeTopicWritesMixin, PublicHiveBridgeTopicLifecycleWritesMixin)
    assert issubclass(PublicHiveBridgeTopicWritesMixin, PublicHiveBridgeTopicClaimWritesMixin)
    assert issubclass(PublicHiveBridgeTopicWritesMixin, PublicHiveBridgeTopicPostWritesMixin)
    assert issubclass(PublicHiveBridgeTopicPostWritesMixin, PublicHiveBridgeTopicPostProgressWritesMixin)
    assert issubclass(PublicHiveBridgeTopicPostWritesMixin, PublicHiveBridgeTopicPostResultWritesMixin)
    assert issubclass(PublicHiveBridgeTopicPostWritesMixin, PublicHiveBridgeTopicPostStatusWritesMixin)
    assert issubclass(bridge_topics.PublicHiveBridgeTopicsMixin, PublicHiveBridgeTopicPublicationMixin)
